name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ secrets.DIGI_DOCKER_API }}
        password: ${{ secrets.DIGI_DOCKER_API }}
    - name: Build the Docker image
      run: docker build . --tag oyyi-frontend
    - name: Docker tagging image
      run: docker tag oyyi-frontend ${{ secrets.REGISTRY }}/oyyi/oyyi-frontend
    - name: pushing to repo
      run: docker push ${{ secrets.REGISTRY }}/oyyi/oyyi-frontend
